#!/bin/bash

# Setting up timezone and clock
ln -sf /usr/share/zoneinfo/Europe/Stockholm /etc/localtime
hwclock --systohc

# Language
touch /etc/locale.conf
sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
sed -i 's/^#sv_SE.UTF-8 UTF-8/sv_SE.UTF-8 UTF-8/' /etc/locale.gen
locale-gen

echo "LANG=C.UTF-8" | tee -a /etc/locale.conf >/dev/null
echo "LC_NUMERIC=sv_SE.UTF-8" | tee -a /etc/locale.conf >/dev/null
echo "LC_TIME=sv_SE.UTF-8" | tee -a /etc/locale.conf >/dev/null
echo "LC_MONETARY=sv_SE.UTF-8" | tee -a /etc/locale.conf >/dev/null
echo "LC_PAPER=sv_SE.UTF-8" | tee -a /etc/locale.conf >/dev/null
echo "LC_MEASUREMENT=sv_SE.UTF-8" | tee -a /etc/locale.conf >/dev/null

# Setting up keymap and terminal font
touch /etc/vconsole.conf
echo "KEYMAP=sv-latin1" | tee -a /etc/vconsole.conf >/dev/null
echo "FONT=ter-124n" | tee -a /etc/vconsole.conf >/dev/null

# Setting up Hostname and Network
touch /etc/hostname
echo "arch-test" | tee -a /etc/hostname >/dev/null

echo "127.0.0.1  localhost" | tee -a /etc/hosts >/dev/null
echo "::  localhost" | tee -a /etc/hosts >/dev/null
echo "127.0.1.1  arch-test" | tee -a /etc/hosts >/dev/null

# Configuring /etc/pacman.conf
sed -i 's/^#Color/Color/' /etc/pacman.conf
sed -i 's/^#ParallelDownloads = 5/ParallelDownloads = 10/' /etc/pacman.conf
nano /etc/pacman.conf

pacman -Sy
pacman -S --noconfirm efibootmgr

bootctl --path=/boot install

# Installing and Configuring Boot Manager
touch /boot/loader/loader.conf
touch /boot/loader/entries/arch.conf
echo "default arch" | tee -a /boot/loader/loader.conf >/dev/null
echo "title Arch Linux" | tee -a /boot/loader/entries/arch.conf >/dev/null
echo "linux vmlinuz-linux" | tee -a /boot/loader/entries/arch.conf >/dev/null
echo "initrd initramfs-linux.img" | tee -a /boot/loader/entries/arch.conf >/dev/null
echo "options root=$(blkid | grep '/dev/vda3' | cut -d' ' -f5 | sed 's/"//g') rw splash lsm=landlock,lockdown,yama,integrity,apparmor,bpf" | tee -a /boot/loader/entries/arch.conf >/dev/null
