#!/bin/bash
# Formatting drives and setting up swap
mkfs.fat -F32 /dev/nvme0n1p1
mkswap /dev/nvme0n1p2
swapon /dev/nvme0n1p2
mkfs.ext4 /dev/nvme0n1p3

# Mounting root partition
mount /dev/nvme0n1p3 /mnt

# Updating pacman
pacman -Syy

# Installing and running reflector
pacman -S reflector
reflector -f 12 -l 12 -n 12 > /etc/pacman.d/mirrorlist

# Setting up pacman.conf
nano /etc/pacman.conf

# Downloading base for install
pacstrap /mnt base base-devel linux linux-firmware nano reflector

# Generating /etc/fstab on new system
genfstab -U /mnt >> /mnt/etc/fstab

# Moving configuration files to new system
mv part2 /mnt
mv moddas /mnt

# Chroot into new system
arch-chroot /mnt
