#!/bin/bash
# Formatting drives and setting up swap
mkfs.fat -F32 /dev/sda1
mkfs.ext4 /dev/sda2

# Mounting root partition
mount /dev/sda2 /mnt

# Setting up pacman.conf
nano /etc/pacman.conf

# Updating pacman
pacman -Syy

# Installing and running reflector
pacman -S --noconfirm reflector
reflector -f 12 -l 12 -n 12 > /etc/pacman.d/mirrorlist

# Downloading base for install
pacstrap /mnt base base-devel linux linux-firmware nano reflector

# Generating /etc/fstab on new system
genfstab -U /mnt >> /mnt/etc/fstab

# Moving configuration files to new system
mv install /mnt

# Chroot into new system
arch-chroot /mnt
